/*Question 2: Increment and Decrement
Description: Write a JavaScript code snippet that initializes a variable with a value of 10. Perform the following operations:

Increment the value by 1 using the increment operator (++).
Decrement the value by 1 using the decrement operator (--).
Print the value after each operation.
*/
let count1 = 10
//decremen

console.log(count1);
console.log(--count1  );
//increment
console.log(count1);
console.log(++count1);

